# Generated by Django 4.0 on 2021-12-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_image')),
                ('english_degree', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermedite', 'Intermedite'), ('Advanced', 'Advanced')], max_length=200)),
                ('coin', models.IntegerField(default=1000)),
                ('phone_number', models.CharField(max_length=13)),
                ('course', models.ManyToManyField(to='api.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
