# Generated by Django 4.0 on 2021-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='github_link',
            field=models.URLField(null=True),
        ),
    ]
